## Data Collection by Web Scraping

In [1]:
from autoscraper import AutoScraper
import pandas as pd

In [46]:
recent=pd.DataFrame()
url='https://www.beeradvocate.com/beer/?view=recent'
scraper = AutoScraper()
brewery_name=['Drekker Brewing Company']
brewery_name = scraper.build(url, brewery_name)
review_profilename=['EMV']
review_profilename = scraper.build(url, review_profilename)
beer_style=['IPA - Black / Cascadian Dark Ale']
beer_style = scraper.build(url, beer_style)
beer_name=['Everybody Love Everybody']
beer_name = scraper.build(url, beer_name)

In [116]:
scraper = AutoScraper()
reviews=['look: 4 | smell: 4 | taste: 4.25 | feel: 4 | overall: 4']
reviews = scraper.build(url, reviews)
review_aroma=[]
review_appearance=[]
review_taste=[]
review_palate=[]
review_overall=[]
for i in reviews:
    i=list(i.split("|"))
    if len(i)<5:
        continue
    review_appearance.append(float(i[0].replace("look:","").strip()))
    review_aroma.append(float(i[1].replace("smell:","").strip()))
    review_taste.append(float(i[2].replace("taste:","").strip()))
    review_palate.append(float(i[3].replace("feel:","").strip()))
    review_overall.append(float(i[4].replace("overall:","").strip())) 

In [117]:
m=min(len(review_overall),len(brewery_name),len(review_profilename),len(beer_style),len(beer_name),len(review_appearance),len(review_aroma),len(review_taste),len(review_palate))
print(m)

25


In [118]:
recent=pd.DataFrame(list(zip(review_overall[:m],brewery_name[:m],review_profilename[:m],beer_style[:m],beer_name[:m],review_appearance[:m],review_aroma[:m],review_taste[:m],review_palate[:m])), columns=['review_overall','brewery_name','review_profilename','beer_style','beer_name','review_appearance','review_aroma','review_taste','review_palate'])
recent.head()

review_overall             brewery_name review_profilename  \
0            4.25  Drekker Brewing Company                EMV   
1            4.00    Bench Brewing Company       thehyperduck   
2            4.00  Artifex Brewing Company           mactrail   
3            4.75     Breckenridge Brewery               hreb   
4            3.50                 Fuller's       LanceBiggums   

                   beer_style                 beer_name  review_appearance  \
0  Sour - Fruited Kettle Sour  Everybody Love Everybody               4.25   
1            Stout - American        Mountainview Stout               3.50   
2              IPA - American                 So Choice               3.75   
3               Winter Warmer             Christmas Ale               4.50   
4                     Old Ale               Vintage Ale               4.25   

   review_aroma  review_taste  review_palate  
0          4.50          4.50           4.25  
1          3.75          4.00           3.75  
2          3.25          3.50           3.50  
3          4.75          4.75           5.00  
4          4.00          3.50           3.25

In [119]:
import math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pylab as pl
%matplotlib inline

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [120]:
pd.options.display.max_rows = 1000
pd.options.display.max_columns = 1000

In [121]:
beers_df = pd.read_csv(r"./BDA Miniproject/beer_reviews.csv" )

In [122]:
beers_df.shape

(1586614, 13)

In [123]:
beers_df=beers_df.drop(['brewery_id','review_time','beer_abv','beer_beerid'],axis=1)

In [124]:
beers_df.head()

brewery_name  review_overall  review_aroma  review_appearance  \
0          Vecchio Birraio             1.5           2.0                2.5   
1          Vecchio Birraio             3.0           2.5                3.0   
2          Vecchio Birraio             3.0           2.5                3.0   
3          Vecchio Birraio             3.0           3.0                3.5   
4  Caldera Brewing Company             4.0           4.5                4.0   

  review_profilename                      beer_style  review_palate  \
0            stcules                      Hefeweizen            1.5   
1            stcules              English Strong Ale            3.0   
2            stcules          Foreign / Export Stout            3.0   
3            stcules                 German Pilsener            2.5   
4     johnmichaelsen  American Double / Imperial IPA            4.0   

   review_taste               beer_name  
0           1.5            Sausa Weizen  
1           3.0                Red Moon  
2           3.0  Black Horse Black Beer  
3           3.0              Sausa Pils  
4           4.5           Cauldron DIPA

In [125]:
beers_df=pd.concat([beers_df,recent])

In [126]:
beers_df.dtypes

brewery_name           object
review_overall        float64
review_aroma          float64
review_appearance     float64
review_profilename     object
beer_style             object
review_palate         float64
review_taste          float64
beer_name              object
dtype: object

In [127]:
beers_df.duplicated().sum()

822

In [128]:
beers_df.drop_duplicates(keep = 'first', inplace = True)

In [129]:
beers_df.duplicated().sum()
beers_df.head()

brewery_name  review_overall  review_aroma  review_appearance  \
0          Vecchio Birraio             1.5           2.0                2.5   
1          Vecchio Birraio             3.0           2.5                3.0   
2          Vecchio Birraio             3.0           2.5                3.0   
3          Vecchio Birraio             3.0           3.0                3.5   
4  Caldera Brewing Company             4.0           4.5                4.0   

  review_profilename                      beer_style  review_palate  \
0            stcules                      Hefeweizen            1.5   
1            stcules              English Strong Ale            3.0   
2            stcules          Foreign / Export Stout            3.0   
3            stcules                 German Pilsener            2.5   
4     johnmichaelsen  American Double / Imperial IPA            4.0   

   review_taste               beer_name  
0           1.5            Sausa Weizen  
1           3.0                Red Moon  
2           3.0  Black Horse Black Beer  
3           3.0              Sausa Pils  
4           4.5           Cauldron DIPA

## Data Exploration

In [130]:
print( 'Unique breweries' )
print( 'By name:', beers_df[ 'brewery_name' ].nunique() )

Unique breweries
By name: 5759


In [131]:
print( 'Unique beers' )
print( 'By name:', beers_df[ 'beer_name' ].nunique() )

Unique beers
By name: 56876


In [132]:
print( 'Unique users:', beers_df[ 'review_profilename' ].nunique() )
print( 'Unique users with more than 1 review:', beers_df[ 'review_profilename' ].value_counts()[ beers_df[ 'review_profilename' ].value_counts() > 1 ].shape[ 0 ], '-' , str( round( beers_df[ 'review_profilename' ].value_counts()[ beers_df[ 'review_profilename' ].value_counts() > 1 ].shape[ 0 ] / beers_df[ 'review_profilename' ].nunique(), 2 ) * 100 ) + '%' )

Unique users: 33403
Unique users with more than 1 review: 22943 - 69.0%


In [133]:
beers_df[ 'review_profilename' ].value_counts().head()

northyorksammy    5814
BuckeyeNation     4661
mikesgroove       4612
Thorpe429         3518
womencantsail     3497
Name: review_profilename, dtype: int64

In [134]:
# A beer subset removing review information is created 
grouped_beers_df = beers_df[ [ 'beer_name', 'brewery_name', 'beer_style' ] ].drop_duplicates()

In [135]:
grouped_beers_df.shape

(65778, 3)

In [136]:
grouped_beers_df.loc[ grouped_beers_df.duplicated( subset = [ 'beer_name' ], keep = False ) ].sort_values( by = 'beer_name'  ).shape

(11483, 3)

In [137]:
# Beers by brewery
grouped_beers_df[ 'brewery_name' ].value_counts( dropna = False ).head()

Rock Bottom Restaurant & Brewery      869
John Harvard's Brewery & Ale House    394
Goose Island Beer Co.                 368
Iron Hill Brewery & Restaurant        316
Minneapolis Town Hall Brewery         312
Name: brewery_name, dtype: int64

In [138]:
# Beers by style
grouped_beers_df[ 'beer_style' ].value_counts( dropna = False ).head()

American IPA                3589
American Pale Ale (APA)     3320
American Amber / Red Ale    2489
American Porter             2181
Fruit / Vegetable Beer      1833
Name: beer_style, dtype: int64

In [139]:
# An new meassure is created by averaging review by factor
beers_df[ 'review_average' ] = round( ( ( beers_df[ 'review_overall' ] + beers_df[ 'review_aroma' ] + beers_df[ 'review_appearance' ] + beers_df[ 'review_palate' ] + beers_df[ 'review_taste' ] ) / 5 ) * 2 ) / 2

## General Filtering

In [140]:
# Defining the linear model
linear_model = LinearRegression( normalize = True )

In [141]:
# Training and generating predictions for the model
linear_model.fit( X = beers_df[ [ 'review_aroma', 'review_appearance', 'review_palate', 'review_taste' ] ], y = beers_df[ 'review_overall' ] )
preds = linear_model.predict( beers_df[ [ 'review_aroma', 'review_appearance', 'review_palate', 'review_taste' ] ] )

In [142]:
# Coeffifients for each feature (aroma, appearance, palate, taste)
linear_model.coef_

array([0.04781174, 0.03587682, 0.25846106, 0.55152083])

In terms of correlation, the ranking seems to be: taste, palate, aroma and appearance. 



These are the beer styles for the top 10 of beers with highest aroma and appearence reviews.

In [143]:
beers_df.sort_values( by = [ 'review_aroma', 'review_appearance' ], ascending = False ).head( 10 ) \
    [ 'beer_style' ].unique().tolist()

['Russian Imperial Stout',
 'American IPA',
 'American Porter',
 'American Double / Imperial IPA',
 'English Bitter',
 'American Pale Ale (APA)',
 'Scotch Ale / Wee Heavy',
 'Scottish Ale',
 'American Blonde Ale']

In [150]:
reviews_count_by_profilename = beers_df.groupby('review_profilename').review_overall.count().to_frame('count_reviews').sort_values(by = "count_reviews", ascending = False)
reviews_count_by_profilename.reset_index(inplace=True)
reviews_count_by_profilename.head()

review_profilename  count_reviews
0     northyorksammy           5814
1      BuckeyeNation           4661
2        mikesgroove           4612
3          Thorpe429           3518
4      womencantsail           3497

In [151]:
reviews_count_user = reviews_count_by_profilename.count_reviews.value_counts().to_frame().reset_index()
reviews_count_user.columns = ['number_of_reviews','number_of_users']
reviews_count_user.head()

number_of_reviews  number_of_users
0                  1            10460
1                  2             4106
2                  3             2427
3                  4             1599
4                  5             1247

In [152]:
reviews_count_user['percentage_users'] = (reviews_count_user['number_of_users']*100)/reviews_count_user.number_of_users.sum()
reviews_count_user['cumul_percentage_users'] = reviews_count_user.percentage_users.cumsum()
reviews_count_user.head()

number_of_reviews  number_of_users  percentage_users  \
0                  1            10460         31.314553   
1                  2             4106         12.292309   
2                  3             2427          7.265814   
3                  4             1599          4.786995   
4                  5             1247          3.733198   

   cumul_percentage_users  
0               31.314553  
1               43.606862  
2               50.872676  
3               55.659671  
4               59.392869

In [163]:
reviews_count_beer_id = beers_df.groupby('beer_name').review_overall.count().to_frame('Reviews_count').sort_values(by = "Reviews_count", ascending=False)
reviews_count_beer_id=reviews_count_beer_id.reset_index()

In [164]:
beer_ids_no_of_ratings_grt_30 = reviews_count_beer_id.loc[reviews_count_beer_id.Reviews_count>=30]['beer_name'].to_frame('beer_name')
users_no_of_ratings_grt_30 = reviews_count_by_profilename.loc[reviews_count_by_profilename.count_reviews>=30].review_profilename.to_frame('review_profilename')

In [167]:
filter_beers_df = pd.merge(beers_df, beer_ids_no_of_ratings_grt_30, how='inner', on='beer_name')
filter_beers_df = pd.merge(rating2, users_no_of_ratings_grt_30, how='inner', on='review_profilename')

## Recommendation Model 

In [168]:
import sklearn
from sklearn.model_selection import train_test_split

In [182]:
train, test = train_test_split(filter_beers_df, test_size=0.32, random_state=31)

In [183]:
print(train.shape)
print(test.shape)

(843333, 10)
(396864, 10)


In [184]:
train.reset_index(inplace=True,drop=True)
test.reset_index(inplace=True,drop=True)
train.head()

brewery_name  review_overall  review_aroma  review_appearance  \
0        Flying Dog Brewery             4.0           3.5                3.0   
1    Tröegs Brewing Company             4.0           4.0                4.0   
2         Deschutes Brewery             4.0           3.5                3.5   
3  AleSmith Brewing Company             4.5           4.5                5.0   
4    Carlow Brewing Company             4.0           4.0                4.5   

  review_profilename                        beer_style  review_palate  \
0            joepais                English Barleywine            3.5   
1           biggred1          American Amber / Red Ale            4.0   
2            GilGarp               American Blonde Ale            4.0   
3          ehammond1  American Double / Imperial Stout            4.5   
4          yelterdow                   Irish Dry Stout            3.5   

   review_taste                              beer_name  review_average  
0           3.5         Horn Dog Barley Wine Style Ale             3.5  
1           4.0               Tröegs Hopback Amber Ale             4.0  
2           3.5                           Twilight Ale             3.5  
3           4.5  AleSmith Speedway Stout - Barrel Aged             4.5  
4           3.5                   O'Hara's Irish Stout             4.0

In [173]:
df_beer_features = train.pivot_table(index='review_profilename',columns='beer_name',values='review_overall').fillna(0)

In [187]:
df_beer_features.head()

beer_name           "Old Yeltsin" Imperial Stout  "Shabadoo" Black & Tan Ale  \
review_profilename                                                             
0110x011                                     0.0                         0.0   
05Harley                                     0.0                         0.0   
0tt0                                         0.0                         0.0   
100floods                                    0.0                         0.0   
1099.0                                       0.0                         0.0   

beer_name           # 100  #'s Ale   #9  't Gaverhopke Extra  \
review_profilename                                             
0110x011              0.0      0.0  0.0                  0.0   
05Harley              0.0      0.0  0.0                  0.0   
0tt0                  0.0      0.0  0.0                  0.0   
100floods             5.0      0.0  0.0                  0.0   
1099.0                0.0      0.0  0.0                  0.0   

beer_name           't Smisje BBBourgondier  't Smisje Blond  \
review_profilename                                             
0110x011                                0.0              0.0   
05Harley                                0.0              0.0   
0tt0                                    0.0              0.0   
100floods                               0.0              0.0   
1099.0                                  0.0              0.0   

beer_name           't Smisje Calva Reserva  't Smisje Dubbel  \
review_profilename                                              
0110x011                                0.0               0.0   
05Harley                                0.0               0.0   
0tt0                                    0.0               0.0   
100floods                               0.0               0.0   
1099.0                                  0.0               0.0   

beer_name           't Smisje Grande Reserva  't Smisje IPA+  't Smisje Kerst  \
review_profilename                                                              
0110x011                                 0.0             0.0              0.0   
05Harley                                 0.0             0.0              0.0   
0tt0                                     0.0             0.0              0.0   
100floods                                0.0             0.0              0.0   
1099.0                                   0.0             0.0              0.0   

beer_name           (512) IPA  (512) Pecan Porter  \
review_profilename                                  
0110x011                  0.0                 0.0   
05Harley                  0.0                 0.0   
0tt0                      0.0                 0.0   
100floods                 0.0                 0.0   
1099.0                    0.0                 0.0   

beer_name           (512) Whiskey Barrel Aged Double Pecan Porter  \
review_profilename                                                  
0110x011                                                      0.0   
05Harley                                                      0.0   
0tt0                                                          0.0   
100floods                                                     0.0   
1099.0                                                        0.0   

beer_name           .357 Imperial Pilsner  10 Commandments  10 Degrees Below  \
review_profilename                                                             
0110x011                              0.0              0.0               0.0   
05Harley                              0.0              0.0               0.0   
0tt0                                  0.0              0.0               0.0   
100floods                             0.0              0.0               0.0   
1099.0                                0.0              0.0               0.0   

beer_name           10 Squared Fish Tale Ale  10.0  100 Meter Ale  \
review_profilename             

In [185]:
dummy_train = train.copy()
dummy_test = test.copy()

In [186]:
dummy_train['review_overall'] = dummy_train['review_overall'].apply(lambda x: 0 if x>=1 else 1)
dummy_test['review_overall'] = dummy_test['review_overall'].apply(lambda x: 1 if x>=1 else 0)

In [190]:
dummy_train = dummy_train.pivot_table(
    index='review_profilename',
    columns='beer_name',
    values='review_overall'
).fillna(1)

dummy_test = dummy_test.pivot_table(
    index='review_profilename',
    columns='beer_name',
    values='review_overall'
).fillna(0)
dummy_train.head()

beer_name           "Old Yeltsin" Imperial Stout  "Shabadoo" Black & Tan Ale  \
review_profilename                                                             
0110x011                                     1.0                         1.0   
05Harley                                     1.0                         1.0   
0tt0                                         1.0                         1.0   
100floods                                    1.0                         1.0   
1099.0                                       1.0                         1.0   

beer_name           # 100  #'s Ale   #9  't Gaverhopke Extra  \
review_profilename                                             
0110x011              1.0      1.0  1.0                  1.0   
05Harley              1.0      1.0  1.0                  1.0   
0tt0                  1.0      1.0  1.0                  1.0   
100floods             0.0      1.0  1.0                  1.0   
1099.0                1.0      1.0  1.0                  1.0   

beer_name           't Smisje BBBourgondier  't Smisje Blond  \
review_profilename                                             
0110x011                                1.0              1.0   
05Harley                                1.0              1.0   
0tt0                                    1.0              1.0   
100floods                               1.0              1.0   
1099.0                                  1.0              1.0   

beer_name           't Smisje Calva Reserva  't Smisje Dubbel  \
review_profilename                                              
0110x011                                1.0               1.0   
05Harley                                1.0               1.0   
0tt0                                    1.0               1.0   
100floods                               1.0               1.0   
1099.0                                  1.0               1.0   

beer_name           't Smisje Grande Reserva  't Smisje IPA+  't Smisje Kerst  \
review_profilename                                                              
0110x011                                 1.0             1.0              1.0   
05Harley                                 1.0             1.0              1.0   
0tt0                                     1.0             1.0              1.0   
100floods                                1.0             1.0              1.0   
1099.0                                   1.0             1.0              1.0   

beer_name           (512) IPA  (512) Pecan Porter  \
review_profilename                                  
0110x011                  1.0                 1.0   
05Harley                  1.0                 1.0   
0tt0                      1.0                 1.0   
100floods                 1.0                 1.0   
1099.0                    1.0                 1.0   

beer_name           (512) Whiskey Barrel Aged Double Pecan Porter  \
review_profilename                                                  
0110x011                                                      1.0   
05Harley                                                      1.0   
0tt0                                                          1.0   
100floods                                                     1.0   
1099.0                                                        1.0   

beer_name           .357 Imperial Pilsner  10 Commandments  10 Degrees Below  \
review_profilename                                                             
0110x011                              1.0              1.0               1.0   
05Harley                              1.0              1.0               1.0   
0tt0                                  1.0              1.0               1.0   
100floods                             1.0              1.0               1.0   
1099.0                                1.0              1.0               1.0   

beer_name           10 Squared Fish Tale Ale  10.0  100 Meter Ale  \
review_profilename             

## User Based Model Using Cosine Similarity

In [174]:
from sklearn.metrics.pairwise import pairwise_distances


user_correlation = 1 - pairwise_distances(df_beer_features, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0

In [175]:
print(user_correlation)

[[1.         0.10668224 0.05271721 ... 0.04844577 0.02213635 0.00714799]
 [0.10668224 1.         0.0654051  ... 0.05567607 0.         0.        ]
 [0.05271721 0.0654051  1.         ... 0.1240652  0.03328539 0.04912214]
 ...
 [0.04844577 0.05567607 0.1240652  ... 1.         0.10047447 0.        ]
 [0.02213635 0.         0.03328539 ... 0.10047447 1.         0.07277543]
 [0.00714799 0.         0.04912214 ... 0.         0.07277543 1.        ]]


In [181]:
user_predicted_ratings = np.dot(user_correlation, df_beer_features.fillna(0))
user_predicted_ratings

array([[ 12.49693785,  19.91421464,  58.15031383, ..., 124.31024133,
         48.28565886,  66.00398164],
       [ 10.53800901,  23.97337772,  54.48312751, ...,  97.02168729,
         46.28361088,  63.15075922],
       [  9.50256632,  20.26892851,  40.09699798, ...,  60.72013102,
         47.46710352,  49.33095048],
       ...,
       [ 10.42889707,  22.05038107,  36.12855045, ...,  60.12861194,
         52.69367117,  46.94870025],
       [ 11.32504243,  21.74833149,  35.73814527, ...,  55.48440881,
         49.25933205,  39.67876557],
       [  6.99840896,  17.80788338,  25.48229588, ...,  39.06348696,
         39.63626531,  36.11485885]])

In [191]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

beer_name           "Old Yeltsin" Imperial Stout  "Shabadoo" Black & Tan Ale  \
review_profilename                                                             
0110x011                               12.496938                   19.914215   
05Harley                               10.538009                   23.973378   
0tt0                                    9.502566                   20.268929   
100floods                               8.564844                   14.261881   
1099.0                                  3.715429                   10.871216   

beer_name               # 100   #'s Ale          #9  't Gaverhopke Extra  \
review_profilename                                                         
0110x011            58.150314  9.135550  181.424206            18.761319   
05Harley            54.483128  8.408105  184.101629            16.567499   
0tt0                40.096998  6.856546  182.497799             9.539259   
100floods            0.000000  6.797478  127.935916            11.018476   
1099.0              12.665719  3.332124  110.731112             3.449477   

beer_name           't Smisje BBBourgondier  't Smisje Blond  \
review_profilename                                             
0110x011                          25.586646         9.276683   
05Harley                          23.079921         8.015560   
0tt0                              18.646435         6.988514   
100floods                         17.964346         7.043421   
1099.0                             6.834016         2.820594   

beer_name           't Smisje Calva Reserva  't Smisje Dubbel  \
review_profilename                                              
0110x011                          22.262313         15.938202   
05Harley                          19.899692         14.791005   
0tt0                              13.338441         10.809494   
100floods                         14.970578         12.355677   
1099.0                             5.171738          4.086629   

beer_name           't Smisje Grande Reserva  't Smisje IPA+  't Smisje Kerst  \
review_profilename                                                              
0110x011                           13.996297       13.204160        16.076727   
05Harley                           10.747171       12.214051        14.711094   
0tt0                                7.202698        9.022555        10.526416   
100floods                           8.110171        9.118639        10.978378   
1099.0                              1.922129        3.514085         3.594635   

beer_name           (512) IPA  (512) Pecan Porter  \
review_profilename                                  
0110x011            12.053103           18.022406   
05Harley            11.000559           16.961621   
0tt0                 8.283143           10.716570   
100floods            9.269633           12.139540   
1099.0               3.673219            4.835492   

beer_name           (512) Whiskey Barrel Aged Double Pecan Porter  \
review_profilename                                                  
0110x011                                                 7.893335   
05Harley                                                 7.164119   
0tt0                                                     4.485813   
100floods                                                4.342429   
1099.0                                                   0.989357   

beer_name           .357 Imperial Pilsner  10 Commandments  10 Degrees Below  \
review_profilename                                                             
0110x011                         7.478208        84.749566          8.283195   
05Harley                         6.427142        69.802413          7.827696   
0tt0                             3.640374        45.333762          6.156730   
100floods                        4.732601        52.340782          6.999295   
1099.0                           1.086146        13.284438          2.934988   

beer_name       

In [192]:
user_final_rating.iloc[0].sort_values(ascending=False)[0:5]

beer_name
Founders Breakfast Stout               589.289218
Old Rasputin Russian Imperial Stout    541.838953
Stone Ruination IPA                    526.061802
Sierra Nevada Celebration Ale          517.661141
Stone IPA (India Pale Ale)             484.142255
Name: 0110x011, dtype: float64

## Item Based using Cosine Similarity

In [194]:
beer_features = train.pivot_table( index='review_profilename', columns='beer_name', values='review_overall' ).T
beer_features.head()

review_profilename            0110x011  05Harley  0tt0  100floods  1099.0  \
beer_name                                                                   
"Old Yeltsin" Imperial Stout       NaN       NaN   NaN        NaN     NaN   
"Shabadoo" Black & Tan Ale         NaN       NaN   NaN        NaN     NaN   
# 100                              NaN       NaN   NaN        5.0     NaN   
#'s Ale                            NaN       NaN   NaN        NaN     NaN   
#9                                 NaN       NaN   NaN        NaN     NaN   

review_profilename            11osixBrew  1759Girl  1Adam12  1fastz28  \
beer_name                                                               
"Old Yeltsin" Imperial Stout         NaN       NaN      NaN       NaN   
"Shabadoo" Black & Tan Ale           NaN       NaN      NaN       NaN   
# 100                                NaN       NaN      NaN       NaN   
#'s Ale                              NaN       NaN      NaN       NaN   
#9                                   NaN       NaN      NaN       NaN   

review_profilename            1morebeer  1whiskey  2BDChicago  2xHops  \
beer_name                                                               
"Old Yeltsin" Imperial Stout        NaN       NaN         NaN     NaN   
"Shabadoo" Black & Tan Ale          NaN       NaN         NaN     NaN   
# 100                               NaN       NaN         NaN     NaN   
#'s Ale                             NaN       NaN         NaN     NaN   
#9                                  NaN       NaN         NaN     3.0   

review_profilename            321jeff  32hoss32  33nickadams  \
beer_name                                                      
"Old Yeltsin" Imperial Stout      NaN       NaN          NaN   
"Shabadoo" Black & Tan Ale        NaN       NaN          NaN   
# 100                             NaN       NaN          NaN   
#'s Ale                           NaN       NaN          NaN   
#9                                NaN       NaN          NaN   

review_profilename            3HovsepiansBrews  3Vandoo  3rdRowTailgater  \
beer_name                                                                  
"Old Yeltsin" Imperial Stout               NaN      NaN              NaN   
"Shabadoo" Black & Tan Ale                 NaN      NaN              NaN   
# 100                                      NaN      NaN              NaN   
#'s Ale                                    NaN      NaN              NaN   
#9                                         NaN      NaN              NaN   

review_profilename            4000qtrap  49degrees  4DAloveofSTOUT  \
beer_name                                                            
"Old Yeltsin" Imperial Stout        NaN        NaN             NaN   
"Shabadoo" Black & Tan Ale          NaN        NaN             NaN   
# 100                               NaN        NaN             NaN   
#'s Ale                             NaN        NaN             NaN   
#9                                  NaN        NaN             NaN   

review_profilename            4thoseabout2bock  51mmz0rz  57andcounting  57md  \
beer_name                                                                       
"Old Yeltsin" Imperial Stout               NaN       NaN            NaN   NaN   
"Shabadoo" Black & Tan Ale                 NaN       NaN            NaN   NaN   
# 100                                      NaN       NaN            NaN   NaN   
#'s Ale                                    NaN       NaN            NaN   NaN   
#9                                         NaN       NaN            4.0   NaN   

review_profilename            67cuda  7beerphil  7ways  828beagle  86MonteSS  \
beer_name                                                                      
"Old Yeltsin" Imperial Stout     NaN        NaN    NaN        NaN        NaN   
"Shabadoo" Black & Tan Ale       NaN        NaN    NaN        NaN        NaN   
# 100                            NaN        NaN    NaN        NaN        Na

In [196]:
from sklearn.metrics.pairwise import pairwise_distances

item_correlation = 1 - pairwise_distances(beer_features.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[1.         0.         0.04656427 ... 0.04744468 0.12137516 0.07372924]
 [0.         1.         0.0096709  ... 0.05376892 0.00879036 0.07595883]
 [0.04656427 0.0096709  1.         ... 0.17272784 0.09776195 0.15992855]
 ...
 [0.04744468 0.05376892 0.17272784 ... 1.         0.12974331 0.19892819]
 [0.12137516 0.00879036 0.09776195 ... 0.12974331 1.         0.12987641]
 [0.07372924 0.07595883 0.15992855 ... 0.19892819 0.12987641 1.        ]]


In [197]:
item_predicted_ratings = np.dot((beer_features.fillna(0).T),item_correlation)
item_predicted_ratings

array([[26.61319596, 20.19008295, 55.50286423, ..., 85.08812264,
        41.10220381, 58.85062094],
       [19.13920092, 22.29266312, 44.95717547, ..., 60.05993083,
        34.23851779, 51.17842568],
       [ 7.57707575,  7.48185361, 13.58837404, ..., 16.11849071,
        14.87722096, 16.78970082],
       ...,
       [ 9.88104902,  9.23192451, 14.24915522, ..., 18.41006072,
        18.57442396, 17.47477724],
       [12.38140798, 11.52410778, 17.64236875, ..., 21.13029392,
        22.13088179, 18.96265476],
       [11.70502216, 13.29618753, 18.1278956 , ..., 21.56057541,
        25.34198289, 23.96930094]])

In [198]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

beer_name           "Old Yeltsin" Imperial Stout  "Shabadoo" Black & Tan Ale  \
review_profilename                                                             
0110x011                               26.613196                   20.190083   
05Harley                               19.139201                   22.292663   
0tt0                                    7.577076                    7.481854   
100floods                              20.902474                   15.445041   
1099.0                                  4.897813                    5.878448   

beer_name               # 100    #'s Ale         #9  't Gaverhopke Extra  \
review_profilename                                                         
0110x011            55.502864  34.457446  54.920457            27.408897   
05Harley            44.957175  25.975381  49.729055            21.584127   
0tt0                13.588374   8.184329  20.588489             5.001115   
100floods            0.000000  30.322941  46.532057            19.632273   
1099.0               6.896070   6.276446  17.392081             2.875398   

beer_name           't Smisje BBBourgondier  't Smisje Blond  \
review_profilename                                             
0110x011                          37.926928        30.417438   
05Harley                          29.460774        23.490462   
0tt0                              10.482102         8.309711   
100floods                         32.864037        27.608452   
1099.0                             6.527111         5.872762   

beer_name           't Smisje Calva Reserva  't Smisje Dubbel  \
review_profilename                                              
0110x011                          38.233443         31.016730   
05Harley                          31.154063         25.696225   
0tt0                               9.269466          7.956161   
100floods                         32.134148         27.853551   
1099.0                             5.644401          3.870072   

beer_name           't Smisje Grande Reserva  't Smisje IPA+  't Smisje Kerst  \
review_profilename                                                              
0110x011                           38.037358       32.246855        34.494670   
05Harley                           27.016888       25.374035        29.155786   
0tt0                                6.573647        8.034156         8.158751   
100floods                          25.427208       27.182570        29.071572   
1099.0                              3.113496        4.598912         4.098185   

beer_name           (512) IPA  (512) Pecan Porter  \
review_profilename                                  
0110x011            22.191827           25.490766   
05Harley            17.414896           21.235232   
0tt0                 4.806813            5.538107   
100floods           18.747179           20.177164   
1099.0               3.620903            4.337272   

beer_name           (512) Whiskey Barrel Aged Double Pecan Porter  \
review_profilename                                                  
0110x011                                                21.595581   
05Harley                                                19.071831   
0tt0                                                     3.898542   
100floods                                               13.514109   
1099.0                                                   1.530739   

beer_name           .357 Imperial Pilsner  10 Commandments  10 Degrees Below  \
review_profilename                                                             
0110x011                        24.482464        68.491379         19.064651   
05Harley                        19.734495        49.607144         16.252971   
0tt0                             3.803264        13.515255          5.366997   
100floods                       16.521970        51.091852         19.743456   
1099.0                           1.802637         6.480615          3.797082   

beer_name       

In [199]:
item_final_rating.iloc[0].sort_values(ascending=False)[0:5]

beer_name
AleSmith Speedway Stout     100.062211
The Abyss                    96.011490
Imperial Stout               95.585053
Founders Breakfast Stout     95.510032
AleSmith IPA                 93.634619
Name: 0110x011, dtype: float64